function [ nF , Omega , BeatWidth   ] = FreeTipFil( FreeTipAngle ,  nF , Fname , OP )



% Time , Angle, X , Y

%% Angle of Tip from the anchor point
% Skip this as in expt. we do not have pivot information
% figure( nF + 100 ),...
%     plot( FreeTipAngle(:,1) , FreeTipAngle(:,2) , 'linewidth' , 2 ),...
%     xlabel('Time (s)'),...
%     set( gca , 'fontsize' , 18 ),...
%     xlim([ 0 FreeTipAngle(end,1)  ]),...
%     ylabel('\phi '),...
%     export_fig( gcf, [ OP , 'PhiFreeTip_', sprintf('%s', Fname) , '.pdf'], '-r300' , '-transparent');
%


%     Mtip = [ ( FreeTipAngle(:,3) - FreeTipAngle(1,3) ),  ( FreeTipAngle(:,4) - FreeTipAngle(1,4) ) ];
%     tmpX = max(   abs( min( Mtip(:,1) )) , max( Mtip(:,1) ) );
%     tmpY = max(   abs( min( Mtip(:,2) )) , max( Mtip(:,2) ) );
%     tmpMax = max( tmpX , tmpY );
%     figure( nF + 200 ),...
%         yyaxis left,...
%         plot( FreeTipAngle(:,1) , Mtip(:,1) , 'linewidth' , 2 ),...
%         ylabel( 'X (\mum)'),...
%         ylim( [ -tmpMax tmpMax ]),...
%         yyaxis right,...
%         plot( FreeTipAngle(:,1) , Mtip(:,2) , 'linewidth' , 2 ),...
%         ylabel('Y (\mum)'),...
%         xlim( [ 0 FreeTipAngle(end,1) ]),...
%         ylim( [ -tmpMax tmpMax ]),...
%         set( gca , 'fontsize' , 18),...
%         export_fig( gcf, [ OP , 'xyFreeTip_', sprintf('%s', Fname ) , '.pdf'], '-r300' , '-transparent');
%

Mtip = [ ( FreeTipAngle(:,3) - FreeTipAngle(1,3) ),  ( FreeTipAngle(:,4) - FreeTipAngle(1,4) ) ];
tmpX = max(   abs( min( Mtip(:,1) )) , max( Mtip(:,1) ) );
tmpY = max(   abs( min( Mtip(:,2) )) , max( Mtip(:,2) ) );
tmpMax = max( tmpX , tmpY );
figure( nF + 1),...
    %yyaxis left,...
    h1= plot( FreeTipAngle(:,1) , Mtip(:,1) ,  'linewidth' , 1.4 ),hold on,...
    ylim( [ -tmpMax tmpMax ]),...
    h2 =plot( FreeTipAngle(:,1) , Mtip(:,2) , 'r' , 'linewidth' , 1.4 ),...
    ylabel('Position (\mum)'),...
    xlim( [ 0 FreeTipAngle(end,1) ]),...
    ylim( [ -tmpMax tmpMax ]),...
    xlabel('Time (s)'),...
    set( gca , 'fontsize' , 18),...
%     yyaxis right,...
%     h3 =plot( FreeTipAngle(:,1) , FreeTipAngle(:,2)  , 'r', 'linewidth' , 1.4 ),hold on,...
%     ylabel('\phi'),...
    legend( [ h1, h2  ] , 'X', 'Y'  , 'location' , 'best' , 'fontsize' , 10),...
    export_fig( gcf, [ OP , 'FreeTipXY_', sprintf('%s', Fname ) , '.pdf'], '-r300' , '-transparent');




figure( nF + 2),...
%     yyaxis left,...
%     h1= plot( FreeTipAngle(:,1) , Mtip(:,1) ,  'linewidth' , 1.4 ),hold on,...
%     ylim( [ -tmpMax tmpMax ]),...
%     h2 =plot( FreeTipAngle(:,1) , Mtip(:,2) , 'k-' , 'linewidth' , 1.4 ),...
%     ylabel('Position (\mum)'),...
%     xlim( [ 0 FreeTipAngle(end,1) ]),...
%     ylim( [ -tmpMax tmpMax ]),...
%     set( gca , 'fontsize' , 18),...
%     yyaxis right,...
    h3 =plot( FreeTipAngle(:,1) , FreeTipAngle(:,2)  , 'k', 'linewidth' , 1.4 ),hold on,...
    ylabel('\phi'),...
     xlim( [ 0 FreeTipAngle(end,1) ]),...
    legend( [  h3 ] , '\phi' , 'location' , 'best' , 'fontsize' , 10),...
     xlabel('Time (s)'),...
      set( gca , 'fontsize' , 18),...
    export_fig( gcf, [ OP , 'FreeTipXYPhi_', sprintf('%s', Fname ) , '.pdf'], '-r300' , '-transparent');
%dlmwrite(  [ OP , 'FreeTipAngle', sprintf('%s', Fname ) ,'.out'] , FreeTipAngle(:,2) ,  'delimiter' , '\t', 'precision','%.6f' );

nF = nF + 4;

BeatWidth = [( abs(min(Mtip(:,1))) + abs(max(Mtip(:,1))) ) , ( abs(min(Mtip(:,2))) + abs(max(Mtip(:,2)))) , max( abs( diff(FreeTipAngle(:,2)))) ];
%dlmwrite( [OP , 'BeatWith', sprintf('%s', Fname ), '.out'] ,  BeatWidth , 'delimiter' , '\t' );
Omega     = abs( diff(FreeTipAngle(:,2)));
end
